# .github/workflows/deploy-supabase-functions.yml

name: Deploy Supabase Functions

on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2

      - name: Determine environment and set project ID
        id: set-project
        run: |
          if [[ "${{ secrets.HELLO }}" == "hello" ]]; then
            echo "hello"
          else
            echo "Unsupported branch: ${{ github.ref }}"
            exit 1
          fi
